import React, { ReactElement } from "react";
import { Box, Center, Text } from "@chakra-ui/react";
import useMQuery from "../hooks/useMediaQuery";
import Head from "next/head";
import CardTitle from "./CardTitle";
import NavBar from "./NavBar";

type Props = { children: ReactElement };

const Layout = ({ children }: Props) => {
  const { isMobile } = useMQuery();
  return (
    <>
      <Head>
        <title>{"Balad'or a la Carte"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_big.png" />
      </Head>
      <main>
        <Box
          maxWidth="1250px"
          width="100%"
          px={isMobile ? "0px" : "80px"}
          margin="auto"
          height="100%"
        >
          <NavBar />
          <Center>
            <Box w="100%">{children}</Box>
          </Center>
        </Box>
      </main>
    </>
  );
};

export default Layout;
