import React, { ReactElement } from "react";
import { Box, Text } from "@chakra-ui/react";
import useMQuery from "../hooks/useMediaQuery";
import Head from "next/head";
import CardTitle from "./CardTitle";
import NavBar from "./NavBar";

type Props = { children: ReactElement };

const Layout = ({ children }: Props) => {
  const { isMobile } = useMQuery();
  return (
    <>
      <Head>
        <title>{"Balad'or a la Carte"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_big.png" />
      </Head>

      <Box>
        <NavBar />
        {children}
      </Box>
    </>
  );
};

export default Layout;
